### PR TITLE
skip threads in case of tagged interfaces

### PR DESCRIPTION
**Pull request by vpiserchia**
This is only a workaround for #12 waiting for upstream to fix this misbehavior.

### CODE REVIEW

**Comment by awelzel** [comment]
Hey @vpiserchia - thanks for the PR! Much appreciated. The "capture" entry can legitimately not be included if I remember correctly (for example if a Napatech card is used).

Could you check for "tcp" instead and also log a warning when this happens including the name of the entry? Possibly extend the tests with you `dump-counters.json` file so we can make sure it won't crash in the future.

If you don't have the cycles, let me know and I'll pick it up.

**Comment by vpiserchia** [comment]
@awelzel added workaround and test data. Please let me know if there is a better way since I'm not so fluent in golang

**Comment by awelzel** [comment]
@vpiserchia , thanks. I've opened a PR on the Suricata side. If that one moves quickly, I'd actually prefer to avoid this workaround in the exporter. Can you use your change locally for now?

I suppose you could also rename the bond interface (or create an alias?).

**Comment by vpiserchia** [comment]
suricata merge process is known to not be that quick still I can surely use a local version of the exporter

**Comment by awelzel** [comment]
@vpiserchia - I'm closing this. Upcoming Suricata 7.0.4 should have this fixed. Thanks for the report.

**Pull request closed without merging**
